### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ktanaka117** [ktanaka117/TrendingGitHub#1]
## RepositoryDetailViewController
- [x] Analysis readme.md (Markdown Text)
- [ ] Download images (jpg, png, gif)
- [ ] Display images (jpg, png, gif)
